 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';


var express = require('express');
var app = express();
var mongoose =require('mongoose');

app.use('/public', express.static(process.cwd() + '/public'));
require('./server/mongoose')();
require('./server/route')(app);



app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

